language: php
php:
  - 7.2
services:
  - mysql
before_script:
  - composer install
script: ./vendor/bin/phpunit ./tests
deploy:
    provider: azure_web_apps
    skip_cleanup: true
    app: sesion6-travis-azure.azurewebsites.net
    site: sesion6-travis-azure.azurewebsites.net
 
  
